---
- name: Install native Linux packages
  ansible.builtin.package:
    name: "{{ category_apps.packages | default([]) }}"
    state: present
  become: true
  when: category_apps.packages | default([]) | length > 0

- name: Install applications after checking for existing installations
  ansible.builtin.include_tasks: application.yml
  loop: "{{ category_apps.apps | default([]) }}"
  loop_control:
    loop_var: application
    label: "{{ application.name }}"
