# Git abbreviations for interactive Fish sessions.
if status is-interactive

    # General and status
    abbr -a 'g' 'git'
    abbr -a 'gst' 'git status'
    abbr -a 'gss' 'git status --short'
    abbr -a 'gsb' 'git status --short --branch'
    abbr -a 'gsnut' 'git status --untracked-files=no'

    # Staging and diffs
    abbr -a 'ga' 'git add'
    abbr -a 'gaa' 'git add --all'
    abbr -a 'gapa' 'git add --patch'
    abbr -a 'gau' 'git add --update'
    abbr -a 'gav' 'git add --verbose'
    abbr -a 'gd' 'git diff'
    abbr -a 'gdca' 'git diff --cached'
    abbr -a 'gdcw' 'git diff --cached --word-diff'
    abbr -a 'gds' 'git diff --staged'
    abbr -a 'gdw' 'git diff --word-diff'
    abbr -a 'gdup' 'git diff @{upstream}'
    abbr -a 'gdt' 'git diff-tree --no-commit-id --name-only -r'
    abbr -a 'grs' 'git restore'
    abbr -a 'grss' 'git restore --source'
    abbr -a 'grst' 'git restore --staged'

    # Branches and checkout
    abbr -a 'gb' 'git branch'
    abbr -a 'gba' 'git branch --all'
    abbr -a 'gbd' 'git branch --delete'
    abbr -a 'gbD' 'git branch --delete --force'
    abbr -a 'gbm' 'git branch --move'
    abbr -a 'gbnm' 'git branch --no-merged'
    abbr -a 'gbr' 'git branch --remotes'
    abbr -a 'gco' 'git checkout'
    abbr -a 'gcor' 'git checkout --recurse-submodules'
    abbr -a 'gcb' 'git checkout -b'
    abbr -a 'gcB' 'git checkout -B'
    abbr -a 'gsw' 'git switch'
    abbr -a 'gswc' 'git switch --create'

    # Commits
    abbr -a 'gc' 'git commit --verbose'
    abbr -a 'gcmsg' 'git commit --message'
    abbr -a 'gca' 'git commit --verbose --all'
    abbr -a 'gcam' 'git commit --all --message'
    abbr -a 'gc!' 'git commit --verbose --amend'
    abbr -a 'gca!' 'git commit --verbose --all --amend'
    abbr -a 'gcan!' 'git commit --verbose --all --no-edit --amend'
    abbr -a 'gcn' 'git commit --verbose --no-edit'
    abbr -a 'gcn!' 'git commit --verbose --no-edit --amend'
    abbr -a 'gcsm' 'git commit --signoff --message'
    abbr -a 'gcs' 'git commit --gpg-sign'
    abbr -a 'gcfu' 'git commit --fixup'

    # History
    abbr -a 'glo' 'git log --oneline --decorate'
    abbr -a 'glg' 'git log --stat'
    abbr -a 'glgp' 'git log --stat --patch'
    abbr -a 'glgg' 'git log --graph'
    abbr -a 'glgga' 'git log --graph --decorate --all'
    abbr -a 'glog' 'git log --oneline --decorate --graph'
    abbr -a 'gloga' 'git log --oneline --decorate --graph --all'
    abbr -a 'glgm' 'git log --graph --max-count=10'
    abbr -a 'gsh' 'git show'
    abbr -a 'gbl' 'git blame -w'
    abbr -a 'grf' 'git reflog'
    abbr -a 'gcount' 'git shortlog --summary --numbered'

    # Remotes and synchronization
    abbr -a 'gf' 'git fetch'
    abbr -a 'gfa' 'git fetch --all --tags --prune'
    abbr -a 'gfo' 'git fetch origin'
    abbr -a 'gl' 'git pull'
    abbr -a 'gpr' 'git pull --rebase'
    abbr -a 'gpra' 'git pull --rebase --autostash'
    abbr -a 'gp' 'git push'
    abbr -a 'gpd' 'git push --dry-run'
    abbr -a 'gpv' 'git push --verbose'
    abbr -a 'gr' 'git remote'
    abbr -a 'grv' 'git remote --verbose'
    abbr -a 'gra' 'git remote add'
    abbr -a 'grrm' 'git remote remove'
    abbr -a 'grmv' 'git remote rename'
    abbr -a 'grset' 'git remote set-url'
    abbr -a 'grup' 'git remote update'
    abbr -a 'gcl' 'git clone --recurse-submodules'

    # Merge, rebase, and cherry-pick
    abbr -a 'gm' 'git merge'
    abbr -a 'gma' 'git merge --abort'
    abbr -a 'gmc' 'git merge --continue'
    abbr -a 'gms' 'git merge --squash'
    abbr -a 'gmff' 'git merge --ff-only'
    abbr -a 'grb' 'git rebase'
    abbr -a 'grba' 'git rebase --abort'
    abbr -a 'grbc' 'git rebase --continue'
    abbr -a 'grbi' 'git rebase --interactive'
    abbr -a 'grbs' 'git rebase --skip'
    abbr -a 'gcp' 'git cherry-pick'
    abbr -a 'gcpa' 'git cherry-pick --abort'
    abbr -a 'gcpc' 'git cherry-pick --continue'

    # Stash
    abbr -a 'gsta' 'git stash push'
    abbr -a 'gstu' 'git stash push --include-untracked'
    abbr -a 'gstaa' 'git stash apply'
    abbr -a 'gstp' 'git stash pop'
    abbr -a 'gstl' 'git stash list'
    abbr -a 'gstd' 'git stash drop'
    abbr -a 'gstc' 'git stash clear'
    abbr -a 'gsts' 'git stash show --patch'
    abbr -a 'gstall' 'git stash --all'

    # Reset, revert, and worktrees
    abbr -a 'grh' 'git reset'
    abbr -a 'gru' 'git reset --'
    abbr -a 'grhh' 'git reset --hard'
    abbr -a 'grhk' 'git reset --keep'
    abbr -a 'grhs' 'git reset --soft'
    abbr -a 'grev' 'git revert'
    abbr -a 'greva' 'git revert --abort'
    abbr -a 'grevc' 'git revert --continue'
    abbr -a 'grm' 'git rm'
    abbr -a 'grmc' 'git rm --cached'
    abbr -a 'gwt' 'git worktree'
    abbr -a 'gwta' 'git worktree add'
    abbr -a 'gwtls' 'git worktree list'
    abbr -a 'gwtmv' 'git worktree move'
    abbr -a 'gwtrm' 'git worktree remove'
end
