---
terminal_config_root: "{{ ansible_facts.env.XDG_CONFIG_HOME | default(ansible_facts.user_dir ~ '/.config', true) }}"
configure_ghostty: true
fisher_bootstrap_url: https://raw.githubusercontent.com/jorgebucaran/fisher/4.4.8/functions/fisher.fish
ghostty_default_config_path: "{{ (shell_home ~ '/Library/Application Support/com.mitchellh.ghostty/config.ghostty') if ansible_facts.system == 'Darwin' else (terminal_config_root ~ '/ghostty/config.ghostty') }}"
terminal_search_path: "{{ (workstation_bin_paths + [ansible_facts.env.PATH]) | join(':') }}"
ghostty_config_paths: "{{ [ghostty_config_path] if ghostty_config_path is defined else [terminal_config_root ~ '/ghostty/config.ghostty', terminal_config_root ~ '/ghostty/config'] + ([shell_home ~ '/Library/Application Support/com.mitchellh.ghostty/config.ghostty', shell_home ~ '/Library/Application Support/com.mitchellh.ghostty/config'] if ansible_facts.system == 'Darwin' else []) }}"
