---
applications_catalog: {}
applications_enabled_categories: "{{ applications_catalog.keys() | list }}"
applications_excluded_categories: []
workplace_only: false
homebrew_search_path: "{{ ansible_facts.env.PATH }}:/opt/homebrew/bin:/usr/local/bin"
applications_home: "{{ ansible_facts.env.HOME }}"
applications_bin_dir: "{{ applications_home }}/.local/bin"
applications_search_path: "{{ applications_bin_dir }}:{{ ansible_facts.env.PATH }}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/snap/bin"
applications_macos_dirs: ["/Applications", "{{ applications_home }}/Applications"]
applications_macos_install_dir: /Applications
